name: Update Pool Schedules

on:
  schedule:
    # Runs every day at 3:00 AM UTC (11 PM ET / 10 PM ET in summer)
    - cron: "0 3 * * *"
  workflow_dispatch:
    # Also allows manual trigger from the GitHub Actions tab

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install chromium --with-deps

      - name: Run scraper
        run: python scrape.py

      - name: Check if schedule_data.json changed
        id: diff
        run: |
          git diff --quiet schedule_data.json && echo "changed=false" >> $GITHUB_OUTPUT || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push updated schedule
        if: steps.diff.outputs.changed == 'true'
        run: |
          git config user.name  "Ottawa Pool Scraper Bot"
          git config user.email "bot@users.noreply.github.com"
          git add schedule_data.json
          git commit -m "chore: update pool schedules $(date -u '+%Y-%m-%d')"
          git push

      - name: No changes detected
        if: steps.diff.outputs.changed == 'false'
        run: echo "Schedule data is already up to date — no commit needed."
